# Generated by Django 4.1.2 on 2022-10-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyric',
            name='date_released',
        ),
        migrations.RemoveField(
            model_name='lyric',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='lyric',
            name='title',
        ),
        migrations.AddField(
            model_name='lyric',
            name='content',
            field=models.TextField(default=' '),
        ),
    ]
